version: '3.8'

services:
  redis:
    image: redis:7.4.7
    ports:
      - "6379:6379"

  web:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
      - MODEL_PATH=/EDSR_x2.pb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./uploads:/uploads
      - ./processed:/processed
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    environment:
      - FLASK_APP=app.py
      - MODEL_PATH=/EDSR_x2.pb
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./uploads:/uploads
      - ./processed:/processed
    depends_on:
      - redis